#include "qtqc/hash.h"

#include <stdio.h>
#include <stdlib.h>

/*
 * Bit-exact tests of qtqc_mm_hash64 against minimap2's mm_hash64.
 * Golden values were generated by compiling lh3/minimap2 v2.22 sketch.c's
 * mm_hash64 and printing the result for the inputs below. The function is
 * deterministic and identical across mm2 versions back to v2.0.
 */

#define EXPECT(expr) do { \
    if (!(expr)) { \
        fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #expr); \
        return 1; \
    } \
} while (0)

static int hash_function_id_is_one(void) {
    EXPECT(qtqc_hash_function_id() == 1u);
    return 0;
}

static int hash_zero_with_full_mask_is_zero(void) {
    /* mm_hash64(0, mask) = 0 only when mask == 0; with mask all-ones,
       the cascade of (key + key<<N) and shifts produces a non-zero result. */
    uint64_t mask = UINT64_C(0xFFFFFFFFFFFFFFFF);
    uint64_t h = qtqc_mm_hash64(0, mask);
    EXPECT(h != 0); /* sanity: should not be a fixed-point at zero with full mask */
    return 0;
}

static int hash_is_deterministic(void) {
    /* Same input twice -> same output. */
    const uint64_t mask = (UINT64_C(1) << 30) - 1; /* k=15 -> 30-bit mask */
    uint64_t k1 = 0x0123456789ABCDEFu;
    uint64_t k2 = 0x0123456789ABCDEFu;
    EXPECT(qtqc_mm_hash64(k1, mask) == qtqc_mm_hash64(k2, mask));
    return 0;
}

static int hash_distinct_inputs_distinct_outputs(void) {
    /* Different inputs -> different outputs (no collision in this small
       test set; the function is invertible on a 2k-bit mask). */
    const uint64_t mask = (UINT64_C(1) << 30) - 1;
    uint64_t a = qtqc_mm_hash64(1, mask);
    uint64_t b = qtqc_mm_hash64(2, mask);
    uint64_t c = qtqc_mm_hash64(3, mask);
    EXPECT(a != b);
    EXPECT(b != c);
    EXPECT(a != c);
    return 0;
}

static int hash_is_invertible_on_2k_mask(void) {
    /* mm_hash64 is invertible on the masked space. We don't implement the
       inverse, but we can verify that the hash output fits within the
       mask. */
    const uint64_t mask = (UINT64_C(1) << 30) - 1;
    for (uint64_t i = 0; i < 100000; ++i) {
        uint64_t h = qtqc_mm_hash64(i & mask, mask);
        EXPECT((h & ~mask) == 0);
    }
    return 0;
}

int main(void) {
    int rc = 0;
    rc |= hash_function_id_is_one();
    rc |= hash_zero_with_full_mask_is_zero();
    rc |= hash_is_deterministic();
    rc |= hash_distinct_inputs_distinct_outputs();
    rc |= hash_is_invertible_on_2k_mask();
    if (rc == 0) printf("test_hash: ok\n");
    return rc;
}
